<a href="https://colab.research.google.com/github/flycye/Pytorch-Training/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

# **Lists**

In [3]:
my_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

#**Nump Arrays**

In [5]:
np1 = np.random.rand(3, 4)
np1


array([[0.99815842, 0.6073956 , 0.28497588, 0.56389367],
       [0.51080483, 0.61038194, 0.67194698, 0.07430814],
       [0.49539733, 0.1823522 , 0.83555417, 0.83860752]])

In [6]:
np1.dtype

dtype('float64')

# **Tensors**
multi-dimensional matrix containing elements of a single data type. default data type of float 32, more suitable for deep learning

argos:
- num of matrices
- rows
- colns

In [7]:
tensor_2d = torch.randn(3, 4)
tensor_2d

tensor([[ 0.3098, -0.6240,  0.3069,  0.0299],
        [ 0.2020,  1.9629,  0.5713,  0.7583],
        [-1.8956, -1.6836,  2.0149, -1.4323]])

In [8]:
tensor_2d.dtype

torch.float32

In [10]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [16]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.9982, 0.6074, 0.2850, 0.5639],
        [0.5108, 0.6104, 0.6719, 0.0743],
        [0.4954, 0.1824, 0.8356, 0.8386]], dtype=torch.float64)

# **Tensor Operations**