<a href="https://colab.research.google.com/github/flycye/Pytorch-Training/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch
import numpy as np

# **Lists**

In [3]:
my_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

#**Numpy Arrays**

In [5]:
np1 = np.random.rand(3, 4)
np1


array([[0.99815842, 0.6073956 , 0.28497588, 0.56389367],
       [0.51080483, 0.61038194, 0.67194698, 0.07430814],
       [0.49539733, 0.1823522 , 0.83555417, 0.83860752]])

In [6]:
np1.dtype

dtype('float64')

# **Tensors**
multi-dimensional matrix containing elements of a single data type. default data type of float 32, more suitable for deep learning

argos:
- num of matrices
- rows
- colns

In [7]:
tensor_2d = torch.randn(3, 4)
tensor_2d

tensor([[ 0.3098, -0.6240,  0.3069,  0.0299],
        [ 0.2020,  1.9629,  0.5713,  0.7583],
        [-1.8956, -1.6836,  2.0149, -1.4323]])

In [8]:
tensor_2d.dtype

torch.float32

In [10]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [16]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.9982, 0.6074, 0.2850, 0.5639],
        [0.5108, 0.6104, 0.6719, 0.0743],
        [0.4954, 0.1824, 0.8356, 0.8386]], dtype=torch.float64)

# **Tensor Operations**

In [18]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# Reshape and View
my_torch = my_torch.reshape(2, 5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [24]:
# if we don't know the number of items, this is how we re-shape
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
my_torch2 = my_torch2.reshape(3, -1)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [27]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
my_torch4 = my_torch3.view(2, 5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
# difference between shape and view
# with reshape and view, they will update, meaning:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
my_torch6 = my_torch5.reshape(2, 5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [9]:
my_torch5[1] = 7
my_torch6

tensor([[0, 7, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
# thus, making a change to the original tensor
# alters the changed tensor too

In [14]:
# slices
my_torch7 = torch.arange(10)
my_torch7

my_torch7[7]  # grabs a specific tensor item

my_torch8 = my_torch7.reshape(5, 2) # mix it up with the reshaping here
my_torch8

# slice torch 8 ! (grab y coordinates only)
my_torch8[:, 1]

tensor([1, 3, 5, 7, 9])

In [15]:
# return a column instead of a list
my_torch8[:, 1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

# **Tensor Math**

In [16]:
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])

In [17]:
# addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [18]:
# addition longhand
torch.add(tensor_a, tensor_b)   # same operation, just with different syntax

tensor([ 6,  8, 10, 12])

In [19]:
# subtract functions
tensor_b - tensor_a
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])